"""settings added setting_type

Revision ID: 0d18e3a37209
Revises: 10640d2c5c02
Create Date: 2022-07-16 22:22:46.643632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d18e3a37209'
down_revision = '10640d2c5c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('setting_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'setting_type')
    # ### end Alembic commands ###
