"""add setting table

Revision ID: 10640d2c5c02
Revises: fbc5fb88e4bc
Create Date: 2022-07-16 21:01:13.875469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10640d2c5c02'
down_revision = 'fbc5fb88e4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_name'), 'setting', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setting_name'), table_name='setting')
    op.drop_table('setting')
    # ### end Alembic commands ###
