"""newsletter table

Revision ID: 4952a5566cff
Revises: 0d18e3a37209
Create Date: 2022-07-17 15:18:42.669064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4952a5566cff'
down_revision = '0d18e3a37209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_timestamp'), 'newsletter', ['timestamp'], unique=False)
    op.create_index(op.f('ix_newsletter_title'), 'newsletter', ['title'], unique=False)
    op.add_column('subscriber', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_subscriber_timestamp'), 'subscriber', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriber_timestamp'), table_name='subscriber')
    op.drop_column('subscriber', 'timestamp')
    op.drop_index(op.f('ix_newsletter_title'), table_name='newsletter')
    op.drop_index(op.f('ix_newsletter_timestamp'), table_name='newsletter')
    op.drop_table('newsletter')
    # ### end Alembic commands ###
